### ISSUE TITLE
phpstan/extension-installer missing ?

### ISSUE THREAD

**Issue by dgoosens** [jakzal/toolbox#421]
hi

I must be missing something...  
but it appears to me the `phpstan/extension-installer` is missing...

I added `symfony` & `doctrine` params in the `phpstan.neon`

```
parameters:
    level: 6
    checkGenericClassInNonGenericObjectType: false
    paths:
        - src
        - tests
    symfony:
        containerXmlPath: var/cache/dev/Common_Infra_Symfony_KernelDevDebugContainer.xml
        consoleApplicationLoader: tests/phpstan/console-loader.php
    scanDirectories:
        - var/cache/dev/Symfony/Config
    doctrine:
        objectManagerLoader: tests/phpstan/doctrine-object-manager.php
```

(as you see, nothing fancy)

but if I invoke 

```bash
docker run --init -it --rm -v "$(pwd):/project" -v "$(pwd)/tmp-phpqa:/tmp" -w /project jakzal/phpqa phpstan analyse -c phpstan.neon
```

I get

```bash
Invalid configuration:
Unexpected item 'parameters › symfony'.
Invalid configuration:
Unexpected item 'parameters › doctrine'.
```

I encounter the same problem if I install `phpstan/phpstan`, `phpstan/phpstan-symfony` & `phpstan/phpstan-doctrine`  
It only works as expected when I also install `phpstan/extension-installer`

I'm pretty sure I'm the one who is doing something wrong...  
But was not able yet to figure out what

Thanks a lot in advance  
dGo
